name: readthedocs-preview
on:
  pull_request:
    paths:
      - "docs/**"
      - poetry.lock
      - pyproject.toml

permissions:
  pull-requests: write

jobs:
  pull-request-links:
    runs-on: ubuntu-latest
    steps:
      - uses: readthedocs/actions/preview@v1
        with:
          project-slug: "pycytominer"